pipeline {
    agent {
        docker {
            image 'maven:3.8.7-openjdk-11' // Maven with OpenJDK 11, adjust as necessary
            args '-v /root/.m2:/root/.m2'  // Optional: Share Maven local repository to cache dependencies
        }
    }
    stages {
        stage('Build') {
            steps {
                sh 'mvn -B -DskipTests clean package'
            }
        }
        stage('Test') {
            steps {
                sh 'mvn test'
            }
            post {
                always {
                    junit 'target/surefire-reports/*.xml'
                }
            }
        }
        stage('Deliver') {
            steps {
                sh './jenkins/scripts/deliver.sh'
            }
        }
    }
}
